var wms_layers = [];
var format_millennials_vs_boomers_local_2016_mye_YOB_for_web_0 = new ol.format.GeoJSON();
var features_millennials_vs_boomers_local_2016_mye_YOB_for_web_0 = format_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.readFeatures(json_millennials_vs_boomers_local_2016_mye_YOB_for_web_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_millennials_vs_boomers_local_2016_mye_YOB_for_web_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.addFeatures(features_millennials_vs_boomers_local_2016_mye_YOB_for_web_0);var lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_millennials_vs_boomers_local_2016_mye_YOB_for_web_0, 
                style: style_millennials_vs_boomers_local_2016_mye_YOB_for_web_0,
    title: 'millennials_vs_boomers_local_2016_mye_YOB_for_web<br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_0.png" />  0.50 - 0.72 <br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_1.png" />  0.72 - 0.82 <br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_2.png" />  0.82 - 1.00 <br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_3.png" />  1.00 - 1.03 <br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_4.png" />  1.03 - 1.35 <br />\
    <img src="styles/legend/millennials_vs_boomers_local_2016_mye_YOB_for_web_0_5.png" />  1.35 - 3.90 <br />'
        });var format_ne_10m_populated_places_1 = new ol.format.GeoJSON();
var features_ne_10m_populated_places_1 = format_ne_10m_populated_places_1.readFeatures(json_ne_10m_populated_places_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ne_10m_populated_places_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_ne_10m_populated_places_1.addFeatures(features_ne_10m_populated_places_1);var lyr_ne_10m_populated_places_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ne_10m_populated_places_1, 
                style: style_ne_10m_populated_places_1,
                title: '<img src="styles/legend/ne_10m_populated_places_1.png" /> ne_10m_populated_places'
            });

lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.setVisible(true);lyr_ne_10m_populated_places_1.setVisible(true);
var layersList = [lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0,lyr_ne_10m_populated_places_1];
lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.set('fieldAliases', {'Area': 'Area', 'Population': 'Population', 'Millennial': 'Millennial', 'Boomers': 'Boomers', 'RatioMtoB': 'RatioMtoB', 'More': 'More', });
lyr_ne_10m_populated_places_1.set('fieldAliases', {'SCALERANK': 'SCALERANK', 'NATSCALE': 'NATSCALE', 'LABELRANK': 'LABELRANK', 'FEATURECLA': 'FEATURECLA', 'NAME': 'NAME', 'NAMEPAR': 'NAMEPAR', 'NAMEALT': 'NAMEALT', 'DIFFASCII': 'DIFFASCII', 'NAMEASCII': 'NAMEASCII', 'ADM0CAP': 'ADM0CAP', 'CAPIN': 'CAPIN', 'WORLDCITY': 'WORLDCITY', 'MEGACITY': 'MEGACITY', 'SOV0NAME': 'SOV0NAME', 'SOV_A3': 'SOV_A3', 'ADM0NAME': 'ADM0NAME', 'ADM0_A3': 'ADM0_A3', 'ADM1NAME': 'ADM1NAME', 'ISO_A2': 'ISO_A2', 'NOTE': 'NOTE', 'LATITUDE': 'LATITUDE', 'LONGITUDE': 'LONGITUDE', 'CHANGED': 'CHANGED', 'NAMEDIFF': 'NAMEDIFF', 'DIFFNOTE': 'DIFFNOTE', 'POP_MAX': 'POP_MAX', 'POP_MIN': 'POP_MIN', 'POP_OTHER': 'POP_OTHER', 'RANK_MAX': 'RANK_MAX', 'RANK_MIN': 'RANK_MIN', 'GEONAMEID': 'GEONAMEID', 'MEGANAME': 'MEGANAME', 'LS_NAME': 'LS_NAME', 'LS_MATCH': 'LS_MATCH', 'CHECKME': 'CHECKME', 'MAX_POP10': 'MAX_POP10', 'MAX_POP20': 'MAX_POP20', 'MAX_POP50': 'MAX_POP50', 'MAX_POP300': 'MAX_POP300', 'MAX_POP310': 'MAX_POP310', 'MAX_NATSCA': 'MAX_NATSCA', 'MIN_AREAKM': 'MIN_AREAKM', 'MAX_AREAKM': 'MAX_AREAKM', 'MIN_AREAMI': 'MIN_AREAMI', 'MAX_AREAMI': 'MAX_AREAMI', 'MIN_PERKM': 'MIN_PERKM', 'MAX_PERKM': 'MAX_PERKM', 'MIN_PERMI': 'MIN_PERMI', 'MAX_PERMI': 'MAX_PERMI', 'MIN_BBXMIN': 'MIN_BBXMIN', 'MAX_BBXMIN': 'MAX_BBXMIN', 'MIN_BBXMAX': 'MIN_BBXMAX', 'MAX_BBXMAX': 'MAX_BBXMAX', 'MIN_BBYMIN': 'MIN_BBYMIN', 'MAX_BBYMIN': 'MAX_BBYMIN', 'MIN_BBYMAX': 'MIN_BBYMAX', 'MAX_BBYMAX': 'MAX_BBYMAX', 'MEAN_BBXC': 'MEAN_BBXC', 'MEAN_BBYC': 'MEAN_BBYC', 'COMPARE': 'COMPARE', 'GN_ASCII': 'GN_ASCII', 'FEATURE_CL': 'FEATURE_CL', 'FEATURE_CO': 'FEATURE_CO', 'ADMIN1_COD': 'ADMIN1_COD', 'GN_POP': 'GN_POP', 'ELEVATION': 'ELEVATION', 'GTOPO30': 'GTOPO30', 'TIMEZONE': 'TIMEZONE', 'GEONAMESNO': 'GEONAMESNO', 'UN_FID': 'UN_FID', 'UN_ADM0': 'UN_ADM0', 'UN_LAT': 'UN_LAT', 'UN_LONG': 'UN_LONG', 'POP1950': 'POP1950', 'POP1955': 'POP1955', 'POP1960': 'POP1960', 'POP1965': 'POP1965', 'POP1970': 'POP1970', 'POP1975': 'POP1975', 'POP1980': 'POP1980', 'POP1985': 'POP1985', 'POP1990': 'POP1990', 'POP1995': 'POP1995', 'POP2000': 'POP2000', 'POP2005': 'POP2005', 'POP2010': 'POP2010', 'POP2015': 'POP2015', 'POP2020': 'POP2020', 'POP2025': 'POP2025', 'POP2050': 'POP2050', 'CITYALT': 'CITYALT', 'min_zoom': 'min_zoom', 'wikidataid': 'wikidataid', 'wof_id': 'wof_id', 'CAPALT': 'CAPALT', 'NAME_EN': 'NAME_EN', 'NAME_DE': 'NAME_DE', 'NAME_ES': 'NAME_ES', 'NAME_FR': 'NAME_FR', 'NAME_PT': 'NAME_PT', 'NAME_RU': 'NAME_RU', 'NAME_ZH': 'NAME_ZH', });
lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.set('fieldImages', {'Area': 'TextEdit', 'Population': 'TextEdit', 'Millennial': 'TextEdit', 'Boomers': 'TextEdit', 'RatioMtoB': 'TextEdit', 'More': 'TextEdit', });
lyr_ne_10m_populated_places_1.set('fieldImages', {'SCALERANK': 'TextEdit', 'NATSCALE': 'TextEdit', 'LABELRANK': 'TextEdit', 'FEATURECLA': 'TextEdit', 'NAME': 'TextEdit', 'NAMEPAR': 'TextEdit', 'NAMEALT': 'TextEdit', 'DIFFASCII': 'TextEdit', 'NAMEASCII': 'TextEdit', 'ADM0CAP': 'TextEdit', 'CAPIN': 'TextEdit', 'WORLDCITY': 'TextEdit', 'MEGACITY': 'TextEdit', 'SOV0NAME': 'TextEdit', 'SOV_A3': 'TextEdit', 'ADM0NAME': 'TextEdit', 'ADM0_A3': 'TextEdit', 'ADM1NAME': 'TextEdit', 'ISO_A2': 'TextEdit', 'NOTE': 'TextEdit', 'LATITUDE': 'TextEdit', 'LONGITUDE': 'TextEdit', 'CHANGED': 'TextEdit', 'NAMEDIFF': 'TextEdit', 'DIFFNOTE': 'TextEdit', 'POP_MAX': 'TextEdit', 'POP_MIN': 'TextEdit', 'POP_OTHER': 'TextEdit', 'RANK_MAX': 'TextEdit', 'RANK_MIN': 'TextEdit', 'GEONAMEID': 'TextEdit', 'MEGANAME': 'TextEdit', 'LS_NAME': 'TextEdit', 'LS_MATCH': 'TextEdit', 'CHECKME': 'TextEdit', 'MAX_POP10': 'TextEdit', 'MAX_POP20': 'TextEdit', 'MAX_POP50': 'TextEdit', 'MAX_POP300': 'TextEdit', 'MAX_POP310': 'TextEdit', 'MAX_NATSCA': 'TextEdit', 'MIN_AREAKM': 'TextEdit', 'MAX_AREAKM': 'TextEdit', 'MIN_AREAMI': 'TextEdit', 'MAX_AREAMI': 'TextEdit', 'MIN_PERKM': 'TextEdit', 'MAX_PERKM': 'TextEdit', 'MIN_PERMI': 'TextEdit', 'MAX_PERMI': 'TextEdit', 'MIN_BBXMIN': 'TextEdit', 'MAX_BBXMIN': 'TextEdit', 'MIN_BBXMAX': 'TextEdit', 'MAX_BBXMAX': 'TextEdit', 'MIN_BBYMIN': 'TextEdit', 'MAX_BBYMIN': 'TextEdit', 'MIN_BBYMAX': 'TextEdit', 'MAX_BBYMAX': 'TextEdit', 'MEAN_BBXC': 'TextEdit', 'MEAN_BBYC': 'TextEdit', 'COMPARE': 'TextEdit', 'GN_ASCII': 'TextEdit', 'FEATURE_CL': 'TextEdit', 'FEATURE_CO': 'TextEdit', 'ADMIN1_COD': 'TextEdit', 'GN_POP': 'TextEdit', 'ELEVATION': 'TextEdit', 'GTOPO30': 'TextEdit', 'TIMEZONE': 'TextEdit', 'GEONAMESNO': 'TextEdit', 'UN_FID': 'TextEdit', 'UN_ADM0': 'TextEdit', 'UN_LAT': 'TextEdit', 'UN_LONG': 'TextEdit', 'POP1950': 'TextEdit', 'POP1955': 'TextEdit', 'POP1960': 'TextEdit', 'POP1965': 'TextEdit', 'POP1970': 'TextEdit', 'POP1975': 'TextEdit', 'POP1980': 'TextEdit', 'POP1985': 'TextEdit', 'POP1990': 'TextEdit', 'POP1995': 'TextEdit', 'POP2000': 'TextEdit', 'POP2005': 'TextEdit', 'POP2010': 'TextEdit', 'POP2015': 'TextEdit', 'POP2020': 'TextEdit', 'POP2025': 'TextEdit', 'POP2050': 'TextEdit', 'CITYALT': 'TextEdit', 'min_zoom': 'TextEdit', 'wikidataid': 'TextEdit', 'wof_id': 'TextEdit', 'CAPALT': 'TextEdit', 'NAME_EN': 'TextEdit', 'NAME_DE': 'TextEdit', 'NAME_ES': 'TextEdit', 'NAME_FR': 'TextEdit', 'NAME_PT': 'TextEdit', 'NAME_RU': 'TextEdit', 'NAME_ZH': 'TextEdit', });
lyr_millennials_vs_boomers_local_2016_mye_YOB_for_web_0.set('fieldLabels', {'Area': 'inline label', 'Population': 'inline label', 'Millennial': 'inline label', 'Boomers': 'inline label', 'RatioMtoB': 'inline label', 'More': 'inline label', });
lyr_ne_10m_populated_places_1.set('fieldLabels', {'SCALERANK': 'no label', 'NATSCALE': 'no label', 'LABELRANK': 'no label', 'FEATURECLA': 'no label', 'NAME': 'no label', 'NAMEPAR': 'no label', 'NAMEALT': 'no label', 'DIFFASCII': 'no label', 'NAMEASCII': 'no label', 'ADM0CAP': 'no label', 'CAPIN': 'no label', 'WORLDCITY': 'no label', 'MEGACITY': 'no label', 'SOV0NAME': 'no label', 'SOV_A3': 'no label', 'ADM0NAME': 'no label', 'ADM0_A3': 'no label', 'ADM1NAME': 'no label', 'ISO_A2': 'no label', 'NOTE': 'no label', 'LATITUDE': 'no label', 'LONGITUDE': 'no label', 'CHANGED': 'no label', 'NAMEDIFF': 'no label', 'DIFFNOTE': 'no label', 'POP_MAX': 'no label', 'POP_MIN': 'no label', 'POP_OTHER': 'no label', 'RANK_MAX': 'no label', 'RANK_MIN': 'no label', 'GEONAMEID': 'no label', 'MEGANAME': 'no label', 'LS_NAME': 'no label', 'LS_MATCH': 'no label', 'CHECKME': 'no label', 'MAX_POP10': 'no label', 'MAX_POP20': 'no label', 'MAX_POP50': 'no label', 'MAX_POP300': 'no label', 'MAX_POP310': 'no label', 'MAX_NATSCA': 'no label', 'MIN_AREAKM': 'no label', 'MAX_AREAKM': 'no label', 'MIN_AREAMI': 'no label', 'MAX_AREAMI': 'no label', 'MIN_PERKM': 'no label', 'MAX_PERKM': 'no label', 'MIN_PERMI': 'no label', 'MAX_PERMI': 'no label', 'MIN_BBXMIN': 'no label', 'MAX_BBXMIN': 'no label', 'MIN_BBXMAX': 'no label', 'MAX_BBXMAX': 'no label', 'MIN_BBYMIN': 'no label', 'MAX_BBYMIN': 'no label', 'MIN_BBYMAX': 'no label', 'MAX_BBYMAX': 'no label', 'MEAN_BBXC': 'no label', 'MEAN_BBYC': 'no label', 'COMPARE': 'no label', 'GN_ASCII': 'no label', 'FEATURE_CL': 'no label', 'FEATURE_CO': 'no label', 'ADMIN1_COD': 'no label', 'GN_POP': 'no label', 'ELEVATION': 'no label', 'GTOPO30': 'no label', 'TIMEZONE': 'no label', 'GEONAMESNO': 'no label', 'UN_FID': 'no label', 'UN_ADM0': 'no label', 'UN_LAT': 'no label', 'UN_LONG': 'no label', 'POP1950': 'no label', 'POP1955': 'no label', 'POP1960': 'no label', 'POP1965': 'no label', 'POP1970': 'no label', 'POP1975': 'no label', 'POP1980': 'no label', 'POP1985': 'no label', 'POP1990': 'no label', 'POP1995': 'no label', 'POP2000': 'no label', 'POP2005': 'no label', 'POP2010': 'no label', 'POP2015': 'no label', 'POP2020': 'no label', 'POP2025': 'no label', 'POP2050': 'no label', 'CITYALT': 'no label', 'min_zoom': 'no label', 'wikidataid': 'no label', 'wof_id': 'no label', 'CAPALT': 'no label', 'NAME_EN': 'no label', 'NAME_DE': 'no label', 'NAME_ES': 'no label', 'NAME_FR': 'no label', 'NAME_PT': 'no label', 'NAME_RU': 'no label', 'NAME_ZH': 'no label', });
lyr_ne_10m_populated_places_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});